# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: OOO "МакМеди"
email: imaklakova@yandex.ru
phone: +7 (916) 547-15-52; +7 (499) 905-56-37
meta-description: > # this means to ignore newlines until "baseurl:"
  ООО МакМеди производство Аппликол Коллаген Коллаплан Склероплант
footer-text: Комфорт хирургу - увереность пациенту
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://makmedi.ru" # the base hostname & protocol for your site, e.g. http://example.com


include: ["_pages"]

sass:
    sass_dir: assets/stylesheets

# Build settings
markdown: kramdown
# theme: minima
gems:
  - jekyll-feed
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
  - backup/

theme: jekyll-theme-minimal